version: 0.0
os: linux
files:
- source: /
 destination: /home/ec2-user/challenge

permissions:
- object: /
   pattern: "**"
   owner: ec2-user
   group: ec2-user

hooks:
ApplicationStop:
   - location: bin/app-stop.sh
     timeout: 10
     runas: ec2-user
     
DownloadBundle:
   - location: bin/downloadbundle.sh
     timeout: 10
     runas: ec2-user
     
BeforeInstall:
   - location: bin/before-install.sh
     timeout: 10
     runas: ec2-user
     
Install:
   - location: bin/install.sh
     timeout: 10
     runas: ec2-user
     
AfterInstall:
   - location: bin/install-pkgs.sh
     timeout: 100
     runas: ec2-user

ApplicationStart:
   - location: bin/app-start.sh
     timeout: 15
     runas: ec2-user
     
ValidateService:
   - location: bin/validate-service.sh
     timeout: 10
     runas: ec2-user
     

